services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${PG_DATASOURCE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    env_file:
      - .env
    ports:
      - "5433:5432"

  backend:
    build: .
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${PG_DATASOURCE}
      DB_USER: ${PG_USERNAME}
      DB_PASSWORD: ${PG_PASSWORD}
      API_PORT: ${API_PORT}
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - database